### ISSUE TITLE
Error while running function generate_all_models()

### ISSUE THREAD

**Issue by tuhina3184** [abelson-lab/Espresso#1]
Hi,

I have been using Espresso with 9 files in mpileupcns format as suggested in the workflow, and it gets stuck at generate_all_models() function with following error : 

_Error in data.frame(FlankingSeqGroup = unique(sample$FlankingSeqGroup),  :
  arguments imply differing number of rows: 0, 1
Calls: %>% -> generate_all_models -> data.frame
Execution halted_

I have made sure there are no missing values in my dataset. i had tried the tool with a different set of samples around last year and it worked completely fine and the files have been generated the same way as before. I am exactly following the tutorial mentioned in the README (https://htmlpreview.github.io/?https://github.com/abelson-lab/Espresso/blob/master/vignettes/Espresso_workflow.html).

Could you please help me out with what I am doing wrong ?
I am attaching 2 of the input files below and also attaching the script I am using. Let me know if I can provide any more files.

Thanks and regards,
Tuhina

[Sample1.txt](https://github.com/abelson-lab/Espresso/files/8668188/Sample1.txt)
[Sample2.txt](https://github.com/abelson-lab/Espresso/files/8668190/Sample2.txt)
[script.txt](https://github.com/abelson-lab/Espresso/files/8668261/script.txt)

**Comment by BioSoft** [comment]
> Tuhina

Hello Tuhina.
It seems that there are at least two problems with your input files. 
for example, in the file Sample1.txt In the VarAllele column, there should be only alternative alleles. You have "#NAME?" for some of the variants.
Also, the MapQual values are very low. In your code, under the function filter_model_input, the MAPQ_cutoff = 59. This will remove all the variants from the sample and cause the error you see.

**Comment by tuhina3184** [comment]
Hi, Thankyou for replying.

I have addressed the issue of MAPQ function and that is now working.
But, "#NAME?" still exists in excel and if viewed in text editor/vim it shows "+G", "-C", "-GC" etc. There's a sign being added to it. Not really sure why that is happening. Any idea ?

Thanks and regards,
Tuhina Srivastava

**Comment by andygxzeng** [comment]
Hi Tuhina,

I think the issue is that some of these indels are interpreted by excel as an equation (e.g. starts with “+” or “-“) and get changed into “#NAME?” when you are exporting from excel to txt.
With that said, the error modelling that Espresso performs to call mutations is designed for single nucleotide substitutions and not for indel detection.

My suggestion is to remove the indel calls from the input file (e.g. only keep rows where VarAllele is a single nucleotide and remove the ones where it is “#NAME?”) and to rerun espresso with the new filtered input file.
Hopefully that helps!

Best,
Andy

From: tuhina3184 ***@***.***>
Date: Tuesday, May 17, 2022 at 12:27 AM
To: abelson-lab/Espresso ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [abelson-lab/Espresso] Error while running function generate_all_models() (Issue #1)

Hi, Thankyou for replying.

I have addressed the issue of MAPQ function and that is now working.
But, "#NAME?" still exists in excel and if viewed in text editor/vim it shows "+G", "-C", "-GC" etc. There's a sign being added to it. Not really sure why that is happening. Any idea ?

Thanks and regards,
Tuhina Srivastava

**Comment by tuhina3184** [comment]
Hi Andy,

Thanks a lot for the input. I will run Espresso without indel calls.

Regards,
Tuhina Srivastava
